---
- name: Install PHP packages
  apt:
    name:
      - php{{ php_version }}-bcmath
      - php{{ php_version }}-cli
      - php{{ php_version }}-gmp
      - php{{ php_version }}-intl
      - php{{ php_version }}-json
      - php{{ php_version }}-mbstring
      - php{{ php_version }}-xdebug
      - php{{ php_version }}-xml
    state: latest

- name: Set timezone for PHP-CLI
  ini_file:
    path: /etc/php/{{ php_version }}/cli/php.ini
    section: Date
    option: date.timezone
    value: "{{ timezone }}"
